---
- name: 文件权限检查
  hosts: localhost
  gather_facts: yes
  user: root
  tasks:
     - name: Get user data for all users on the system
       get_users:
         min_uid: 0
       register: user_list
       check_mode: yes


     - debug:
         var: user_list
